/* 
 * Accounting API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: api@xero.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Xero.NetStandard.OAuth2.Api;
using Xero.NetStandard.OAuth2.Model;
using Xero.NetStandard.OAuth2.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Xero.NetStandard.OAuth2.Test.Model.Accounting
{
    /// <summary>
    ///  Class for testing JournalLine
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class JournalLineTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for JournalLine
        //private JournalLine instance;

        public JournalLineTests()
        {
            // TODO uncomment below to create an instance of JournalLine
            //instance = new JournalLine();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of JournalLine
        /// </summary>
        [Fact]
        public void JournalLineInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" JournalLine
            //Assert.IsInstanceOfType<JournalLine> (instance, "variable 'instance' is a JournalLine");
        }


        /// <summary>
        /// Test the property 'JournalLineID'
        /// </summary>
        [Fact]
        public void JournalLineIDTest()
        {
            // TODO unit test for the property 'JournalLineID'
        }
        /// <summary>
        /// Test the property 'AccountID'
        /// </summary>
        [Fact]
        public void AccountIDTest()
        {
            // TODO unit test for the property 'AccountID'
        }
        /// <summary>
        /// Test the property 'AccountCode'
        /// </summary>
        [Fact]
        public void AccountCodeTest()
        {
            // TODO unit test for the property 'AccountCode'
        }
        /// <summary>
        /// Test the property 'AccountType'
        /// </summary>
        [Fact]
        public void AccountTypeTest()
        {
            // TODO unit test for the property 'AccountType'
        }
        /// <summary>
        /// Test the property 'AccountName'
        /// </summary>
        [Fact]
        public void AccountNameTest()
        {
            // TODO unit test for the property 'AccountName'
        }
        /// <summary>
        /// Test the property 'Description'
        /// </summary>
        [Fact]
        public void DescriptionTest()
        {
            // TODO unit test for the property 'Description'
        }
        /// <summary>
        /// Test the property 'NetAmount'
        /// </summary>
        [Fact]
        public void NetAmountTest()
        {
            // TODO unit test for the property 'NetAmount'
        }
        /// <summary>
        /// Test the property 'GrossAmount'
        /// </summary>
        [Fact]
        public void GrossAmountTest()
        {
            // TODO unit test for the property 'GrossAmount'
        }
        /// <summary>
        /// Test the property 'TaxAmount'
        /// </summary>
        [Fact]
        public void TaxAmountTest()
        {
            // TODO unit test for the property 'TaxAmount'
        }
        /// <summary>
        /// Test the property 'TaxType'
        /// </summary>
        [Fact]
        public void TaxTypeTest()
        {
            // TODO unit test for the property 'TaxType'
        }
        /// <summary>
        /// Test the property 'TaxName'
        /// </summary>
        [Fact]
        public void TaxNameTest()
        {
            // TODO unit test for the property 'TaxName'
        }
        /// <summary>
        /// Test the property 'TrackingCategories'
        /// </summary>
        [Fact]
        public void TrackingCategoriesTest()
        {
            // TODO unit test for the property 'TrackingCategories'
        }

    }

}
