/* 
 * Accounting API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: api@xero.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Xero.NetStandard.OAuth2.Api;
using Xero.NetStandard.OAuth2.Model;
using Xero.NetStandard.OAuth2.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Xero.NetStandard.OAuth2.Test.Model.Accounting
{
    /// <summary>
    ///  Class for testing Organisations
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class OrganisationsTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for Organisations
        //private Organisations instance;

        public OrganisationsTests()
        {
            // TODO uncomment below to create an instance of Organisations
            //instance = new Organisations();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of Organisations
        /// </summary>
        [Fact]
        public void OrganisationsInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" Organisations
            //Assert.IsInstanceOfType<Organisations> (instance, "variable 'instance' is a Organisations");
        }


        /// <summary>
        /// Test the property '_Organisations'
        /// </summary>
        [Fact]
        public void _OrganisationsTest()
        {
            // TODO unit test for the property '_Organisations'
        }

    }

}
