/*
 * Xero Accounting API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 6.1.1
 * Contact: api@xero.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Org.OpenAPITools.Client.OpenAPIDateConverter;

namespace Org.OpenAPITools.Model
{
    /// <summary>
    /// CISOrgSetting
    /// </summary>
    [DataContract(Name = "CISOrgSetting")]
    public partial class CISOrgSetting : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="CISOrgSetting" /> class.
        /// </summary>
        /// <param name="cISContractorEnabled">true or false - Boolean that describes if the organisation is a CIS Contractor.</param>
        /// <param name="cISSubContractorEnabled">true or false - Boolean that describes if the organisation is a CIS SubContractor.</param>
        public CISOrgSetting(bool cISContractorEnabled = default(bool), bool cISSubContractorEnabled = default(bool))
        {
            this.CISContractorEnabled = cISContractorEnabled;
            this.CISSubContractorEnabled = cISSubContractorEnabled;
        }

        /// <summary>
        /// true or false - Boolean that describes if the organisation is a CIS Contractor
        /// </summary>
        /// <value>true or false - Boolean that describes if the organisation is a CIS Contractor</value>
        [DataMember(Name = "CISContractorEnabled", EmitDefaultValue = true)]
        public bool CISContractorEnabled { get; set; }

        /// <summary>
        /// true or false - Boolean that describes if the organisation is a CIS SubContractor
        /// </summary>
        /// <value>true or false - Boolean that describes if the organisation is a CIS SubContractor</value>
        [DataMember(Name = "CISSubContractorEnabled", EmitDefaultValue = true)]
        public bool CISSubContractorEnabled { get; set; }

        /// <summary>
        /// CIS Deduction rate for the organisation
        /// </summary>
        /// <value>CIS Deduction rate for the organisation</value>
        [DataMember(Name = "Rate", EmitDefaultValue = false)]
        public double Rate { get; private set; }

        /// <summary>
        /// Returns false as Rate should not be serialized given that it's read-only.
        /// </summary>
        /// <returns>false (boolean)</returns>
        public bool ShouldSerializeRate()
        {
            return false;
        }
        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class CISOrgSetting {\n");
            sb.Append("  CISContractorEnabled: ").Append(CISContractorEnabled).Append("\n");
            sb.Append("  CISSubContractorEnabled: ").Append(CISSubContractorEnabled).Append("\n");
            sb.Append("  Rate: ").Append(Rate).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
