/*
 * Xero Accounting API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 6.1.1
 * Contact: api@xero.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Org.OpenAPITools.Client.OpenAPIDateConverter;

namespace Org.OpenAPITools.Model
{
    /// <summary>
    /// The date when the organisation starts using Xero
    /// </summary>
    [DataContract(Name = "ConversionDate")]
    public partial class ConversionDate : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ConversionDate" /> class.
        /// </summary>
        /// <param name="month">The month the organisation starts using Xero. Value is an integer between 1 and 12.</param>
        /// <param name="year">The year the organisation starts using Xero. Value is an integer greater than 2006.</param>
        public ConversionDate(int month = default(int), int year = default(int))
        {
            this.Month = month;
            this.Year = year;
        }

        /// <summary>
        /// The month the organisation starts using Xero. Value is an integer between 1 and 12
        /// </summary>
        /// <value>The month the organisation starts using Xero. Value is an integer between 1 and 12</value>
        /// <example>1</example>
        [DataMember(Name = "Month", EmitDefaultValue = false)]
        public int Month { get; set; }

        /// <summary>
        /// The year the organisation starts using Xero. Value is an integer greater than 2006
        /// </summary>
        /// <value>The year the organisation starts using Xero. Value is an integer greater than 2006</value>
        /// <example>2020</example>
        [DataMember(Name = "Year", EmitDefaultValue = false)]
        public int Year { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class ConversionDate {\n");
            sb.Append("  Month: ").Append(Month).Append("\n");
            sb.Append("  Year: ").Append(Year).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
