/*
 * Xero Accounting API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 6.1.1
 * Contact: api@xero.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Org.OpenAPITools.Client.OpenAPIDateConverter;

namespace Org.OpenAPITools.Model
{
    /// <summary>
    /// Setup
    /// </summary>
    [DataContract(Name = "Setup")]
    public partial class Setup : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="Setup" /> class.
        /// </summary>
        /// <param name="conversionDate">conversionDate.</param>
        /// <param name="conversionBalances">Balance supplied for each account that has a value as at the conversion date..</param>
        /// <param name="accounts">accounts.</param>
        public Setup(ConversionDate conversionDate = default(ConversionDate), List<ConversionBalances> conversionBalances = default(List<ConversionBalances>), List<Account> accounts = default(List<Account>))
        {
            this.ConversionDate = conversionDate;
            this.ConversionBalances = conversionBalances;
            this.Accounts = accounts;
        }

        /// <summary>
        /// Gets or Sets ConversionDate
        /// </summary>
        [DataMember(Name = "ConversionDate", EmitDefaultValue = false)]
        public ConversionDate ConversionDate { get; set; }

        /// <summary>
        /// Balance supplied for each account that has a value as at the conversion date.
        /// </summary>
        /// <value>Balance supplied for each account that has a value as at the conversion date.</value>
        [DataMember(Name = "ConversionBalances", EmitDefaultValue = false)]
        public List<ConversionBalances> ConversionBalances { get; set; }

        /// <summary>
        /// Gets or Sets Accounts
        /// </summary>
        [DataMember(Name = "Accounts", EmitDefaultValue = false)]
        public List<Account> Accounts { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class Setup {\n");
            sb.Append("  ConversionDate: ").Append(ConversionDate).Append("\n");
            sb.Append("  ConversionBalances: ").Append(ConversionBalances).Append("\n");
            sb.Append("  Accounts: ").Append(Accounts).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
