/* 
 * Xero Payroll NZ
 *
 * This is the Xero Payroll API for orgs in the NZ region.
 *
 * The version of the OpenAPI document: 2.7.0
 * Contact: api@xero.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Xero.NetStandard.OAuth2.Api;
using Xero.NetStandard.OAuth2.Model.PayrollNz;
using Xero.NetStandard.OAuth2.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Xero.NetStandard.OAuth2.Test.Model.PayrollNz
{
    /// <summary>
    ///  Class for testing Employment
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class EmploymentTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for Employment
        //private Employment instance;

        public EmploymentTests()
        {
            // TODO uncomment below to create an instance of Employment
            //instance = new Employment();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of Employment
        /// </summary>
        [Fact]
        public void EmploymentInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" Employment
            //Assert.IsInstanceOfType<Employment> (instance, "variable 'instance' is a Employment");
        }


        /// <summary>
        /// Test the property 'PayrollCalendarID'
        /// </summary>
        [Fact]
        public void PayrollCalendarIDTest()
        {
            // TODO unit test for the property 'PayrollCalendarID'
        }
        /// <summary>
        /// Test the property 'PayRunCalendarID'
        /// </summary>
        [Fact]
        public void PayRunCalendarIDTest()
        {
            // TODO unit test for the property 'PayRunCalendarID'
        }
        /// <summary>
        /// Test the property 'StartDate'
        /// </summary>
        [Fact]
        public void StartDateTest()
        {
            // TODO unit test for the property 'StartDate'
        }

    }

}
