/* 
 * Xero Payroll NZ
 *
 * This is the Xero Payroll API for orgs in the NZ region.
 *
 * The version of the OpenAPI document: 2.7.0
 * Contact: api@xero.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Xero.NetStandard.OAuth2.Api;
using Xero.NetStandard.OAuth2.Model.PayrollNz;
using Xero.NetStandard.OAuth2.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Xero.NetStandard.OAuth2.Test.Model.PayrollNz
{
    /// <summary>
    ///  Class for testing EmployeeLeaveSetupObject
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class EmployeeLeaveSetupObjectTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for EmployeeLeaveSetupObject
        //private EmployeeLeaveSetupObject instance;

        public EmployeeLeaveSetupObjectTests()
        {
            // TODO uncomment below to create an instance of EmployeeLeaveSetupObject
            //instance = new EmployeeLeaveSetupObject();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of EmployeeLeaveSetupObject
        /// </summary>
        [Fact]
        public void EmployeeLeaveSetupObjectInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" EmployeeLeaveSetupObject
            //Assert.IsInstanceOfType<EmployeeLeaveSetupObject> (instance, "variable 'instance' is a EmployeeLeaveSetupObject");
        }


        /// <summary>
        /// Test the property 'Pagination'
        /// </summary>
        [Fact]
        public void PaginationTest()
        {
            // TODO unit test for the property 'Pagination'
        }
        /// <summary>
        /// Test the property 'Problem'
        /// </summary>
        [Fact]
        public void ProblemTest()
        {
            // TODO unit test for the property 'Problem'
        }
        /// <summary>
        /// Test the property 'LeaveSetup'
        /// </summary>
        [Fact]
        public void LeaveSetupTest()
        {
            // TODO unit test for the property 'LeaveSetup'
        }

    }

}
