/* 
 * Xero Payroll NZ
 *
 * This is the Xero Payroll API for orgs in the NZ region.
 *
 * The version of the OpenAPI document: 2.7.0
 * Contact: api@xero.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Xero.NetStandard.OAuth2.Api;
using Xero.NetStandard.OAuth2.Model.PayrollNz;
using Xero.NetStandard.OAuth2.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Xero.NetStandard.OAuth2.Test.Model.PayrollNz
{
    /// <summary>
    ///  Class for testing EmployeeTax
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class EmployeeTaxTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for EmployeeTax
        //private EmployeeTax instance;

        public EmployeeTaxTests()
        {
            // TODO uncomment below to create an instance of EmployeeTax
            //instance = new EmployeeTax();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of EmployeeTax
        /// </summary>
        [Fact]
        public void EmployeeTaxInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" EmployeeTax
            //Assert.IsInstanceOfType<EmployeeTax> (instance, "variable 'instance' is a EmployeeTax");
        }


        /// <summary>
        /// Test the property 'IrdNumber'
        /// </summary>
        [Fact]
        public void IrdNumberTest()
        {
            // TODO unit test for the property 'IrdNumber'
        }
        /// <summary>
        /// Test the property 'TaxCode'
        /// </summary>
        [Fact]
        public void TaxCodeTest()
        {
            // TODO unit test for the property 'TaxCode'
        }
        /// <summary>
        /// Test the property 'SpecialTaxRatePercentage'
        /// </summary>
        [Fact]
        public void SpecialTaxRatePercentageTest()
        {
            // TODO unit test for the property 'SpecialTaxRatePercentage'
        }
        /// <summary>
        /// Test the property 'HasSpecialStudentLoanRate'
        /// </summary>
        [Fact]
        public void HasSpecialStudentLoanRateTest()
        {
            // TODO unit test for the property 'HasSpecialStudentLoanRate'
        }
        /// <summary>
        /// Test the property 'SpecialStudentLoanRatePercentage'
        /// </summary>
        [Fact]
        public void SpecialStudentLoanRatePercentageTest()
        {
            // TODO unit test for the property 'SpecialStudentLoanRatePercentage'
        }
        /// <summary>
        /// Test the property 'IsEligibleForKiwiSaver'
        /// </summary>
        [Fact]
        public void IsEligibleForKiwiSaverTest()
        {
            // TODO unit test for the property 'IsEligibleForKiwiSaver'
        }
        /// <summary>
        /// Test the property 'EsctRatePercentage'
        /// </summary>
        [Fact]
        public void EsctRatePercentageTest()
        {
            // TODO unit test for the property 'EsctRatePercentage'
        }
        /// <summary>
        /// Test the property 'KiwiSaverContributions'
        /// </summary>
        [Fact]
        public void KiwiSaverContributionsTest()
        {
            // TODO unit test for the property 'KiwiSaverContributions'
        }
        /// <summary>
        /// Test the property 'KiwiSaverEmployeeContributionRatePercentage'
        /// </summary>
        [Fact]
        public void KiwiSaverEmployeeContributionRatePercentageTest()
        {
            // TODO unit test for the property 'KiwiSaverEmployeeContributionRatePercentage'
        }
        /// <summary>
        /// Test the property 'KiwiSaverEmployerContributionRatePercentage'
        /// </summary>
        [Fact]
        public void KiwiSaverEmployerContributionRatePercentageTest()
        {
            // TODO unit test for the property 'KiwiSaverEmployerContributionRatePercentage'
        }
        /// <summary>
        /// Test the property 'KiwiSaverEmployerSalarySacrificeContributionRatePercentage'
        /// </summary>
        [Fact]
        public void KiwiSaverEmployerSalarySacrificeContributionRatePercentageTest()
        {
            // TODO unit test for the property 'KiwiSaverEmployerSalarySacrificeContributionRatePercentage'
        }
        /// <summary>
        /// Test the property 'KiwiSaverOptOutDate'
        /// </summary>
        [Fact]
        public void KiwiSaverOptOutDateTest()
        {
            // TODO unit test for the property 'KiwiSaverOptOutDate'
        }
        /// <summary>
        /// Test the property 'KiwiSaverContributionHolidayEndDate'
        /// </summary>
        [Fact]
        public void KiwiSaverContributionHolidayEndDateTest()
        {
            // TODO unit test for the property 'KiwiSaverContributionHolidayEndDate'
        }
        /// <summary>
        /// Test the property 'HasStudentLoanBalance'
        /// </summary>
        [Fact]
        public void HasStudentLoanBalanceTest()
        {
            // TODO unit test for the property 'HasStudentLoanBalance'
        }
        /// <summary>
        /// Test the property 'StudentLoanBalance'
        /// </summary>
        [Fact]
        public void StudentLoanBalanceTest()
        {
            // TODO unit test for the property 'StudentLoanBalance'
        }
        /// <summary>
        /// Test the property 'StudentLoanAsAt'
        /// </summary>
        [Fact]
        public void StudentLoanAsAtTest()
        {
            // TODO unit test for the property 'StudentLoanAsAt'
        }

    }

}
