/* 
 * Xero Payroll NZ
 *
 * This is the Xero Payroll API for orgs in the NZ region.
 *
 * The version of the OpenAPI document: 2.7.0
 * Contact: api@xero.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Xero.NetStandard.OAuth2.Api;
using Xero.NetStandard.OAuth2.Model.PayrollNz;
using Xero.NetStandard.OAuth2.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Xero.NetStandard.OAuth2.Test.Model.PayrollNz
{
    /// <summary>
    ///  Class for testing LeavePeriod
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class LeavePeriodTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for LeavePeriod
        //private LeavePeriod instance;

        public LeavePeriodTests()
        {
            // TODO uncomment below to create an instance of LeavePeriod
            //instance = new LeavePeriod();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of LeavePeriod
        /// </summary>
        [Fact]
        public void LeavePeriodInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" LeavePeriod
            //Assert.IsInstanceOfType<LeavePeriod> (instance, "variable 'instance' is a LeavePeriod");
        }


        /// <summary>
        /// Test the property 'PeriodStartDate'
        /// </summary>
        [Fact]
        public void PeriodStartDateTest()
        {
            // TODO unit test for the property 'PeriodStartDate'
        }
        /// <summary>
        /// Test the property 'PeriodEndDate'
        /// </summary>
        [Fact]
        public void PeriodEndDateTest()
        {
            // TODO unit test for the property 'PeriodEndDate'
        }
        /// <summary>
        /// Test the property 'NumberOfUnits'
        /// </summary>
        [Fact]
        public void NumberOfUnitsTest()
        {
            // TODO unit test for the property 'NumberOfUnits'
        }
        /// <summary>
        /// Test the property 'PeriodStatus'
        /// </summary>
        [Fact]
        public void PeriodStatusTest()
        {
            // TODO unit test for the property 'PeriodStatus'
        }

    }

}
