/* 
 * Xero Payroll NZ
 *
 * This is the Xero Payroll API for orgs in the NZ region.
 *
 * The version of the OpenAPI document: 2.7.0
 * Contact: api@xero.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Xero.NetStandard.OAuth2.Api;
using Xero.NetStandard.OAuth2.Model.PayrollNz;
using Xero.NetStandard.OAuth2.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Xero.NetStandard.OAuth2.Test.Model.PayrollNz
{
    /// <summary>
    ///  Class for testing Reimbursement
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ReimbursementTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for Reimbursement
        //private Reimbursement instance;

        public ReimbursementTests()
        {
            // TODO uncomment below to create an instance of Reimbursement
            //instance = new Reimbursement();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of Reimbursement
        /// </summary>
        [Fact]
        public void ReimbursementInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" Reimbursement
            //Assert.IsInstanceOfType<Reimbursement> (instance, "variable 'instance' is a Reimbursement");
        }


        /// <summary>
        /// Test the property 'ReimbursementID'
        /// </summary>
        [Fact]
        public void ReimbursementIDTest()
        {
            // TODO unit test for the property 'ReimbursementID'
        }
        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'AccountID'
        /// </summary>
        [Fact]
        public void AccountIDTest()
        {
            // TODO unit test for the property 'AccountID'
        }
        /// <summary>
        /// Test the property 'CurrentRecord'
        /// </summary>
        [Fact]
        public void CurrentRecordTest()
        {
            // TODO unit test for the property 'CurrentRecord'
        }
        /// <summary>
        /// Test the property 'ReimbursementCategory'
        /// </summary>
        [Fact]
        public void ReimbursementCategoryTest()
        {
            // TODO unit test for the property 'ReimbursementCategory'
        }
        /// <summary>
        /// Test the property 'CalculationType'
        /// </summary>
        [Fact]
        public void CalculationTypeTest()
        {
            // TODO unit test for the property 'CalculationType'
        }
        /// <summary>
        /// Test the property 'StandardAmount'
        /// </summary>
        [Fact]
        public void StandardAmountTest()
        {
            // TODO unit test for the property 'StandardAmount'
        }
        /// <summary>
        /// Test the property 'StandardTypeOfUnits'
        /// </summary>
        [Fact]
        public void StandardTypeOfUnitsTest()
        {
            // TODO unit test for the property 'StandardTypeOfUnits'
        }
        /// <summary>
        /// Test the property 'StandardRatePerUnit'
        /// </summary>
        [Fact]
        public void StandardRatePerUnitTest()
        {
            // TODO unit test for the property 'StandardRatePerUnit'
        }

    }

}
