/* 
 * Xero Payroll NZ
 *
 * This is the Xero Payroll API for orgs in the NZ region.
 *
 * Contact: api@xero.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Xero.NetStandard.OAuth2.Client.OpenAPIDateConverter;

namespace Xero.NetStandard.OAuth2.Model.PayrollNz
{
    /// <summary>
    /// EmployeeWorkingPattern
    /// </summary>
    [DataContract]
    public partial class EmployeeWorkingPattern :  IEquatable<EmployeeWorkingPattern>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="EmployeeWorkingPattern" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        public EmployeeWorkingPattern() 
        { 
        }
        
        /// <summary>
        /// The Xero identifier for for Employee working pattern
        /// </summary>
        /// <value>The Xero identifier for for Employee working pattern</value>
        [DataMember(Name="payeeWorkingPatternID", EmitDefaultValue=false)]
        public Guid? PayeeWorkingPatternID { get; set; }

        /// <summary>
        /// The effective date of the corresponding salary and wages
        /// </summary>
        /// <value>The effective date of the corresponding salary and wages</value>
        [DataMember(Name="effectiveFrom", EmitDefaultValue=false)]
        [JsonConverter(typeof(OpenAPIDateConverter))]
        public DateTime? EffectiveFrom { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class EmployeeWorkingPattern {\n");
            sb.Append("  PayeeWorkingPatternID: ").Append(PayeeWorkingPatternID).Append("\n");
            sb.Append("  EffectiveFrom: ").Append(EffectiveFrom).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as EmployeeWorkingPattern);
        }

        /// <summary>
        /// Returns true if EmployeeWorkingPattern instances are equal
        /// </summary>
        /// <param name="input">Instance of EmployeeWorkingPattern to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(EmployeeWorkingPattern input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.PayeeWorkingPatternID == input.PayeeWorkingPatternID ||
                    (this.PayeeWorkingPatternID != null &&
                    this.PayeeWorkingPatternID.Equals(input.PayeeWorkingPatternID))
                ) && 
                (
                    this.EffectiveFrom == input.EffectiveFrom ||
                    (this.EffectiveFrom != null &&
                    this.EffectiveFrom.Equals(input.EffectiveFrom))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.PayeeWorkingPatternID != null)
                    hashCode = hashCode * 59 + this.PayeeWorkingPatternID.GetHashCode();
                if (this.EffectiveFrom != null)
                    hashCode = hashCode * 59 + this.EffectiveFrom.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
