/* 
 * Xero Payroll AU
 *
 * This is the Xero Payroll API for orgs in Australia region.
 *
 * The version of the OpenAPI document: 2.8.0
 * Contact: api@xero.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Xero.NetStandard.OAuth2.Api;
using Xero.NetStandard.OAuth2.Model.PayrollAu;
using Xero.NetStandard.OAuth2.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Xero.NetStandard.OAuth2.Test.Model.PayrollAu
{
    /// <summary>
    ///  Class for testing LeaveAccrualLine
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class LeaveAccrualLineTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for LeaveAccrualLine
        //private LeaveAccrualLine instance;

        public LeaveAccrualLineTests()
        {
            // TODO uncomment below to create an instance of LeaveAccrualLine
            //instance = new LeaveAccrualLine();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of LeaveAccrualLine
        /// </summary>
        [Fact]
        public void LeaveAccrualLineInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" LeaveAccrualLine
            //Assert.IsInstanceOfType<LeaveAccrualLine> (instance, "variable 'instance' is a LeaveAccrualLine");
        }


        /// <summary>
        /// Test the property 'LeaveTypeID'
        /// </summary>
        [Fact]
        public void LeaveTypeIDTest()
        {
            // TODO unit test for the property 'LeaveTypeID'
        }
        /// <summary>
        /// Test the property 'NumberOfUnits'
        /// </summary>
        [Fact]
        public void NumberOfUnitsTest()
        {
            // TODO unit test for the property 'NumberOfUnits'
        }
        /// <summary>
        /// Test the property 'AutoCalculate'
        /// </summary>
        [Fact]
        public void AutoCalculateTest()
        {
            // TODO unit test for the property 'AutoCalculate'
        }

    }

}
