/* 
 * Xero Payroll AU
 *
 * This is the Xero Payroll API for orgs in Australia region.
 *
 * The version of the OpenAPI document: 2.8.0
 * Contact: api@xero.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Xero.NetStandard.OAuth2.Api;
using Xero.NetStandard.OAuth2.Model.PayrollAu;
using Xero.NetStandard.OAuth2.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Xero.NetStandard.OAuth2.Test.Model.PayrollAu
{
    /// <summary>
    ///  Class for testing LeaveTypeContributionType
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class LeaveTypeContributionTypeTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for LeaveTypeContributionType
        //private LeaveTypeContributionType instance;

        public LeaveTypeContributionTypeTests()
        {
            // TODO uncomment below to create an instance of LeaveTypeContributionType
            //instance = new LeaveTypeContributionType();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of LeaveTypeContributionType
        /// </summary>
        [Fact]
        public void LeaveTypeContributionTypeInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" LeaveTypeContributionType
            //Assert.IsInstanceOfType<LeaveTypeContributionType> (instance, "variable 'instance' is a LeaveTypeContributionType");
        }



    }

}
