/* 
 * Xero Payroll AU
 *
 * This is the Xero Payroll API for orgs in Australia region.
 *
 * The version of the OpenAPI document: 2.8.0
 * Contact: api@xero.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Xero.NetStandard.OAuth2.Api;
using Xero.NetStandard.OAuth2.Model.PayrollAu;
using Xero.NetStandard.OAuth2.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Xero.NetStandard.OAuth2.Test.Model.PayrollAu
{
    /// <summary>
    ///  Class for testing SettingsObject
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class SettingsObjectTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for SettingsObject
        //private SettingsObject instance;

        public SettingsObjectTests()
        {
            // TODO uncomment below to create an instance of SettingsObject
            //instance = new SettingsObject();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of SettingsObject
        /// </summary>
        [Fact]
        public void SettingsObjectInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" SettingsObject
            //Assert.IsInstanceOfType<SettingsObject> (instance, "variable 'instance' is a SettingsObject");
        }


        /// <summary>
        /// Test the property 'Settings'
        /// </summary>
        [Fact]
        public void SettingsTest()
        {
            // TODO unit test for the property 'Settings'
        }

    }

}
