/* 
 * Accounting API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: api@xero.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Xero.NetStandard.OAuth2.Api;
using Xero.NetStandard.OAuth2.Model;
using Xero.NetStandard.OAuth2.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Xero.NetStandard.OAuth2.Test
{
    /// <summary>
    ///  Class for testing CISSetting
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class CISSettingTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for CISSetting
        //private CISSetting instance;

        public CISSettingTests()
        {
            // TODO uncomment below to create an instance of CISSetting
            //instance = new CISSetting();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of CISSetting
        /// </summary>
        [Fact]
        public void CISSettingInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" CISSetting
            //Assert.IsInstanceOfType<CISSetting> (instance, "variable 'instance' is a CISSetting");
        }


        /// <summary>
        /// Test the property 'CISEnabled'
        /// </summary>
        [Fact]
        public void CISEnabledTest()
        {
            // TODO unit test for the property 'CISEnabled'
        }
        /// <summary>
        /// Test the property 'Rate'
        /// </summary>
        [Fact]
        public void RateTest()
        {
            // TODO unit test for the property 'Rate'
        }

    }

}
