/* 
 * Accounting API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: api@xero.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Xero.NetStandard.OAuth2.Api;
using Xero.NetStandard.OAuth2.Model;
using Xero.NetStandard.OAuth2.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Xero.NetStandard.OAuth2.Test
{
    /// <summary>
    ///  Class for testing Prepayments
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class PrepaymentsTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for Prepayments
        //private Prepayments instance;

        public PrepaymentsTests()
        {
            // TODO uncomment below to create an instance of Prepayments
            //instance = new Prepayments();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of Prepayments
        /// </summary>
        [Fact]
        public void PrepaymentsInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" Prepayments
            //Assert.IsInstanceOfType<Prepayments> (instance, "variable 'instance' is a Prepayments");
        }


        /// <summary>
        /// Test the property '_Prepayments'
        /// </summary>
        [Fact]
        public void _PrepaymentsTest()
        {
            // TODO unit test for the property '_Prepayments'
        }

    }

}
