/* 
 * Accounting API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: api@xero.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Xero.NetStandard.OAuth2.Api;
using Xero.NetStandard.OAuth2.Model;
using Xero.NetStandard.OAuth2.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Xero.NetStandard.OAuth2.Test
{
    /// <summary>
    ///  Class for testing ReportWithRows
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ReportWithRowsTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ReportWithRows
        //private ReportWithRows instance;

        public ReportWithRowsTests()
        {
            // TODO uncomment below to create an instance of ReportWithRows
            //instance = new ReportWithRows();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ReportWithRows
        /// </summary>
        [Fact]
        public void ReportWithRowsInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" ReportWithRows
            //Assert.IsInstanceOfType<ReportWithRows> (instance, "variable 'instance' is a ReportWithRows");
        }


        /// <summary>
        /// Test the property 'Reports'
        /// </summary>
        [Fact]
        public void ReportsTest()
        {
            // TODO unit test for the property 'Reports'
        }

    }

}
