/*
 * Xero Accounting API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 6.1.1
 * Contact: api@xero.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing Allocations
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class AllocationsTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for Allocations
        //private Allocations instance;

        public AllocationsTests()
        {
            // TODO uncomment below to create an instance of Allocations
            //instance = new Allocations();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of Allocations
        /// </summary>
        [Fact]
        public void AllocationsInstanceTest()
        {
            // TODO uncomment below to test "IsType" Allocations
            //Assert.IsType<Allocations>(instance);
        }

        /// <summary>
        /// Test the property 'VarAllocations'
        /// </summary>
        [Fact]
        public void VarAllocationsTest()
        {
            // TODO unit test for the property 'VarAllocations'
        }
    }
}
