/*
 * Xero Accounting API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 6.1.1
 * Contact: api@xero.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing BatchPaymentDetails
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class BatchPaymentDetailsTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for BatchPaymentDetails
        //private BatchPaymentDetails instance;

        public BatchPaymentDetailsTests()
        {
            // TODO uncomment below to create an instance of BatchPaymentDetails
            //instance = new BatchPaymentDetails();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of BatchPaymentDetails
        /// </summary>
        [Fact]
        public void BatchPaymentDetailsInstanceTest()
        {
            // TODO uncomment below to test "IsType" BatchPaymentDetails
            //Assert.IsType<BatchPaymentDetails>(instance);
        }

        /// <summary>
        /// Test the property 'BankAccountNumber'
        /// </summary>
        [Fact]
        public void BankAccountNumberTest()
        {
            // TODO unit test for the property 'BankAccountNumber'
        }

        /// <summary>
        /// Test the property 'BankAccountName'
        /// </summary>
        [Fact]
        public void BankAccountNameTest()
        {
            // TODO unit test for the property 'BankAccountName'
        }

        /// <summary>
        /// Test the property 'Details'
        /// </summary>
        [Fact]
        public void DetailsTest()
        {
            // TODO unit test for the property 'Details'
        }

        /// <summary>
        /// Test the property 'Code'
        /// </summary>
        [Fact]
        public void CodeTest()
        {
            // TODO unit test for the property 'Code'
        }

        /// <summary>
        /// Test the property 'Reference'
        /// </summary>
        [Fact]
        public void ReferenceTest()
        {
            // TODO unit test for the property 'Reference'
        }
    }
}
