/*
 * Xero Accounting API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 6.1.1
 * Contact: api@xero.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing BatchPaymentDelete
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class BatchPaymentDeleteTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for BatchPaymentDelete
        //private BatchPaymentDelete instance;

        public BatchPaymentDeleteTests()
        {
            // TODO uncomment below to create an instance of BatchPaymentDelete
            //instance = new BatchPaymentDelete();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of BatchPaymentDelete
        /// </summary>
        [Fact]
        public void BatchPaymentDeleteInstanceTest()
        {
            // TODO uncomment below to test "IsType" BatchPaymentDelete
            //Assert.IsType<BatchPaymentDelete>(instance);
        }

        /// <summary>
        /// Test the property 'BatchPaymentID'
        /// </summary>
        [Fact]
        public void BatchPaymentIDTest()
        {
            // TODO unit test for the property 'BatchPaymentID'
        }

        /// <summary>
        /// Test the property 'Status'
        /// </summary>
        [Fact]
        public void StatusTest()
        {
            // TODO unit test for the property 'Status'
        }
    }
}
