/*
 * Xero Accounting API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 6.1.1
 * Contact: api@xero.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing Currencies
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class CurrenciesTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for Currencies
        //private Currencies instance;

        public CurrenciesTests()
        {
            // TODO uncomment below to create an instance of Currencies
            //instance = new Currencies();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of Currencies
        /// </summary>
        [Fact]
        public void CurrenciesInstanceTest()
        {
            // TODO uncomment below to test "IsType" Currencies
            //Assert.IsType<Currencies>(instance);
        }

        /// <summary>
        /// Test the property 'VarCurrencies'
        /// </summary>
        [Fact]
        public void VarCurrenciesTest()
        {
            // TODO unit test for the property 'VarCurrencies'
        }
    }
}
