/*
 * Xero Accounting API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 6.1.1
 * Contact: api@xero.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing ImportSummary
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ImportSummaryTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ImportSummary
        //private ImportSummary instance;

        public ImportSummaryTests()
        {
            // TODO uncomment below to create an instance of ImportSummary
            //instance = new ImportSummary();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ImportSummary
        /// </summary>
        [Fact]
        public void ImportSummaryInstanceTest()
        {
            // TODO uncomment below to test "IsType" ImportSummary
            //Assert.IsType<ImportSummary>(instance);
        }

        /// <summary>
        /// Test the property 'Accounts'
        /// </summary>
        [Fact]
        public void AccountsTest()
        {
            // TODO unit test for the property 'Accounts'
        }

        /// <summary>
        /// Test the property 'Organisation'
        /// </summary>
        [Fact]
        public void OrganisationTest()
        {
            // TODO unit test for the property 'Organisation'
        }
    }
}
