/*
 * Xero Accounting API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 6.1.1
 * Contact: api@xero.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing Invoices
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class InvoicesTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for Invoices
        //private Invoices instance;

        public InvoicesTests()
        {
            // TODO uncomment below to create an instance of Invoices
            //instance = new Invoices();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of Invoices
        /// </summary>
        [Fact]
        public void InvoicesInstanceTest()
        {
            // TODO uncomment below to test "IsType" Invoices
            //Assert.IsType<Invoices>(instance);
        }

        /// <summary>
        /// Test the property 'Pagination'
        /// </summary>
        [Fact]
        public void PaginationTest()
        {
            // TODO unit test for the property 'Pagination'
        }

        /// <summary>
        /// Test the property 'Warnings'
        /// </summary>
        [Fact]
        public void WarningsTest()
        {
            // TODO unit test for the property 'Warnings'
        }

        /// <summary>
        /// Test the property 'VarInvoices'
        /// </summary>
        [Fact]
        public void VarInvoicesTest()
        {
            // TODO unit test for the property 'VarInvoices'
        }
    }
}
