/*
 * Xero Accounting API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 6.1.1
 * Contact: api@xero.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing PaymentTermType
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class PaymentTermTypeTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for PaymentTermType
        //private PaymentTermType instance;

        public PaymentTermTypeTests()
        {
            // TODO uncomment below to create an instance of PaymentTermType
            //instance = new PaymentTermType();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of PaymentTermType
        /// </summary>
        [Fact]
        public void PaymentTermTypeInstanceTest()
        {
            // TODO uncomment below to test "IsType" PaymentTermType
            //Assert.IsType<PaymentTermType>(instance);
        }
    }
}
