/*
 * Xero Accounting API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 6.1.1
 * Contact: api@xero.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing TaxType
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class TaxTypeTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for TaxType
        //private TaxType instance;

        public TaxTypeTests()
        {
            // TODO uncomment below to create an instance of TaxType
            //instance = new TaxType();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of TaxType
        /// </summary>
        [Fact]
        public void TaxTypeInstanceTest()
        {
            // TODO uncomment below to test "IsType" TaxType
            //Assert.IsType<TaxType>(instance);
        }
    }
}
