/*
 * Xero Accounting API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 6.1.1
 * Contact: api@xero.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing TrackingCategory
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class TrackingCategoryTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for TrackingCategory
        //private TrackingCategory instance;

        public TrackingCategoryTests()
        {
            // TODO uncomment below to create an instance of TrackingCategory
            //instance = new TrackingCategory();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of TrackingCategory
        /// </summary>
        [Fact]
        public void TrackingCategoryInstanceTest()
        {
            // TODO uncomment below to test "IsType" TrackingCategory
            //Assert.IsType<TrackingCategory>(instance);
        }

        /// <summary>
        /// Test the property 'TrackingCategoryID'
        /// </summary>
        [Fact]
        public void TrackingCategoryIDTest()
        {
            // TODO unit test for the property 'TrackingCategoryID'
        }

        /// <summary>
        /// Test the property 'TrackingOptionID'
        /// </summary>
        [Fact]
        public void TrackingOptionIDTest()
        {
            // TODO unit test for the property 'TrackingOptionID'
        }

        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }

        /// <summary>
        /// Test the property 'Option'
        /// </summary>
        [Fact]
        public void OptionTest()
        {
            // TODO unit test for the property 'Option'
        }

        /// <summary>
        /// Test the property 'Status'
        /// </summary>
        [Fact]
        public void StatusTest()
        {
            // TODO unit test for the property 'Status'
        }

        /// <summary>
        /// Test the property 'Options'
        /// </summary>
        [Fact]
        public void OptionsTest()
        {
            // TODO unit test for the property 'Options'
        }
    }
}
