/*
 * Xero Accounting API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 6.1.1
 * Contact: api@xero.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing Users
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class UsersTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for Users
        //private Users instance;

        public UsersTests()
        {
            // TODO uncomment below to create an instance of Users
            //instance = new Users();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of Users
        /// </summary>
        [Fact]
        public void UsersInstanceTest()
        {
            // TODO uncomment below to test "IsType" Users
            //Assert.IsType<Users>(instance);
        }

        /// <summary>
        /// Test the property 'VarUsers'
        /// </summary>
        [Fact]
        public void VarUsersTest()
        {
            // TODO unit test for the property 'VarUsers'
        }
    }
}
