name: .NET Build & Test

on: 
  push:
  pull_request:
    branches:
      - master

jobs:
  build_and_test:
    uses: ./.github/workflows/build-test-reusable.yml
    with:
      dotnet-version: 3.1.x
