name: .NET Publish

on:
  release:
    types: [published]

jobs:
  build_and_test:
    uses: ./.github/workflows/build-test-reusable.yml
    with:
      dotnet-version: 3.1.x
  
  publish:
    runs-on: ubuntu-latest
    needs: build_and_test
    steps:
    - uses: actions/checkout@v4.1.7
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4.0.1
      with:
        dotnet-version: 3.1.x
    
    - name: Create Package for Nuget.org
      run: dotnet pack
    - name: Publish Package to Nuget.org
      run: dotnet nuget push ./Xero.NetStandard.OAuth2/bin/Debug/Xero.NetStandard.OAuth2.${{ github.event.release.name }}.nupkg --api-key ${{ secrets.NUGET_APIKEY }} --source https://api.nuget.org/v3/index.json
